title: Opvizor's home
description: This is the technical home for Opvizor the performance analyzer!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Official Website: https://opvizor.com/
