title: Opvizor's home
description: This is the technical home for Opvizor the performance analyzer!
theme: just-the-docs

url: https://codenotary.github.io/opvizor/

aux_links:
  Official Website: https://opvizor.com/
